server:
  port: 8085

spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    pe.edu.vallegrande.report_service: DEBUG